package:
  name: rnalien
  version: '1.3.2'

source:
  fn: 1.3.2.tar.gz
  url: https://github.com/eggzilla/RNAlien/archive/1.3.2.tar.gz

build:
  number: 0
  skip: True  #  [osx]

requirements:
  build:
    - stack >=1.2.0
    - perl-threaded
    - gmp
    - zlib

  run:
    - viennarna ==2.3.3
    - rnaz >=2.1
    - locarna ==1.9.1
    - infernal >=1.1.2
    - gmp
    - perl-threaded
    - libgcc

test:
  commands:
    - RNAlien -?

about:
  home: http://rna.tbi.univie.ac.at/rnalien/tool
  license: GPL-3
  summary: A tool for unsupervised construction of RNA family models
