{% set version = "1.0.0" %}

package:
  name: pnnl-atlas
  version: {{ version }}

source:
  fn: atlas-{{ version }}.tar.gz
  url: https://github.com/pnnl/atlas/archive/v{{ version }}.tar.gz
  sha256: b1af6ce034188538db06b56319b37f9c08a5428470cdd97efddace81ec19fd66

build:
  number: 0
  skip: True # [py27]

requirements:
  build:
    - python
    - setuptools
    - click
    - pandas
    - pyyaml
  run:
    - python
    - click
    - pandas
    - pyyaml
    - snakemake
    - bbmap
    - diamond
    - maxbin2
    - megahit
    - prodigal
    - samtools
    - spades
    - subread

test:
    imports:
      - atlas
    commands:
      - atlas --help > /dev/null

about:
  home: https://github.com/pnnl/atlas
  license: BSD-3-Clause
  summary: "ATLAS - a comprehensive infrastructure for assembly, annotation, and genomic binning of metagenomic and metatranscriptomic data"
