package:
  name: dinopy
  version: "1.2.1"

source:
  fn: dinopy-1.2.1.tar.gz
  url: https://pypi.python.org/packages/f8/7a/b8ffa56c2f3e68ce7326269596cde7bcfd928d80d4807f683a6f6362d00a/dinopy-1.2.1.tar.gz
  md5: bdf13cc060787a3943befe5845786316

build:
  skip: True # [py27]
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9

  run:
    - python
    - numpy >=1.9

test:
  # Python imports
  imports:
    - dinopy

about:
  home: https://bitbucket.org/HenningTimm/dinopy
  license: MIT License
  summary: 'DNA input and output library for Python and Cython. Includes reader and writer for FASTA and FASTQ files, support for samtools faidx files, and generators for solid and gapped q-grams (k-mers).'