{% set version="0.8.1" %}
build:
  number: 0
  # OSX failing due to libary issues even though shipping with Salmon binary
  # dyld: Library not loaded: /usr/local/opt/tbb/lib/libtbbmalloc_proxy.dylib
  # https://travis-ci.org/bioconda/bioconda-recipes/jobs/211785820#L295
  skip: true # [osx]

about:
    home: https://github.com/COMBINE-lab/salmon
    license: GPLv3
    summary: Highly-accurate & wicked fast transcript-level quantification from RNA-seq reads using lightweight alignments

package:
    name: salmon
    version: {{ version }}

source:
  fn: Salmon-{{ version }}_linux_x86_64.tar.gz # [linux]
  url: https://github.com/COMBINE-lab/salmon/releases/download/v{{ version }}/Salmon-{{ version }}_linux_x86_64.tar.gz # [linux]
  md5: a0e2d72b33fc571c28a6ce8aef1201fd # [linux]
  fn: Salmon-{{ version }}_macOS_10.12.tar.gz # [osx]
  url: https://github.com/COMBINE-lab/salmon/releases/download/v{{ version }}/Salmon-{{ version }}_macOS_10.12.tar.gz # [osx]
  md5: 28473afefa199a4bb0b7a3625ff48793 # [osx]


requirements:
  build:
  run:

test:
    commands:
      - salmon --help
